apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-service
  namespace: smartbank
spec:
  replicas: 1
  selector:
    matchLabels: { app: customer-service }
  template:
    metadata:
      labels: { app: customer-service }
    spec:
      containers:
      - name: customer-service
        image: customer-service:0.1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8082
        readinessProbe:
          httpGet: { path: /actuator/health, port: 8082 }
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          httpGet: { path: /actuator/health, port: 8082 }
          initialDelaySeconds: 20
          periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: customer-service
  namespace: smartbank
spec:
  selector: { app: customer-service }
  ports:
  - port: 8082
    targetPort: 8082
